### ISSUE TITLE
ip-range and VPC name

### ISSUE THREAD

**Issue by ahmadshadid** [ahmed-abdelazim/shadid#1]
After rerunning the code with terraform, because same VPC range and name was used I needed to manually change the vac name since DO doesn't allow you to delete a VPC, and also had to change vac-ip range before deployment because I tried to deploy and I was alerted that it will overlap with pre existing VPC range.

**Comment by ahmed-abdelazim** [comment]
You can set your VPC ip range setting the variable `vpc_ip_range`
Default is `"10.10.10.0/24"` you can set it to whatever private subnet you want

**Comment by ahmadshadid** [comment]
thanks it works fine.
also I deployed 5 do_count 
1-the instance with index number 4. named instance 3 docker was not installed inside.
2-if I want to scale up now after I already deployed the first 5 how can I do it ?

**Comment by ahmed-abdelazim** [comment]
1- Just wait for a minute fr the initial script to finish and install Docker
 2- Just change count and re-deploy, Terraform will notify you the changes then you confirm
